repos:
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    - id: flake8
      args:
        ['--config=.flake8']
      additional_dependencies: [
        flake8-docstrings,
        flake8_quotes,
        flake8_commas,
        flake8_builtins,
        pep8-naming,
        flake8-variables-names,
        flake8-bugbear,
        import-order,
        flake8-length,
        flake8-mock,
        flake8-pytest,
      ]
